name: Updates changelog and releases
# You can automate releases when pushing on master branch. Recommanded using git flow or equivalent.
# on:
#   push:
#     branches:
#       - "master"
#       - "main"

# or when using a version tag on the a master or main branch. Not recommanded if “Conventional Changelog Action” is used to tag already.
# on:
#   push:
#     tags:
#       - "v*.*.*"
#     branches:
#       - "master"
#       - "main"

# to manually trigger the action
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
on: workflow_dispatch

jobs:
  Updates changelog and releases:
    runs-on: ubuntu-latest

    steps:
      - run: echo "🐧 This job is running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      # allow workflow to access repository under $GITHUB_WORKSPACE
      - name: Check out repository code
        uses: actions/checkout@v3

      # This action will bump version, tag commit and generate a changelog with conventional commits.
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          version-file: "./package.json"

      # Deprecated. Use another action
      - name: create release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

      - run: echo "🍏 This job's status is ${{ job.status }}."
